name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write # Grant write permissions for the GITHUB_TOKEN
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: List build output
      run: ls -la build/ # Add this step to verify build directory contents
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build 